[icons]
"󰣪" = { ord = 9, tui = ["cargo", "nix", "gcc", "g++", "rustc", "clang"] }
"" = { ord = 8, font_size = "1.5rem", gui = ["librewolf", "firefox", "vivaldi", "vivaldi-stable", "chromium"] }
"󰝚" = { ord = 7, gui = [ "psst-gui"] }
"󰅩" = { ord = 6, font_size = "1.5rem", tui = [".hx-wrapped", "hx", "vim", "nvim", "nano"] }
"" = { ord = 5, gui = ["org.gnome.Nautilus"], tui = ["lf", "fx", "nnn"] }
"" = { ord = 4, font_size = "1.0rem", gui = ["kitty", "foot", "alacritty"] }
"" = { ord = 3, gui = ["geary", "thunderbird"] }
"" = { other = true }
"" = { active = true }
"" = { empty = true }

